export enum ContentType { 
    JSON = "application/json",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    FORM_DATA = "multipart/form-data",
    TEXT_PLAIN = "text/plain",
    HTML = "text/html",
    CSS = "text/css",
    XML = "application/xml",
    OCTET_STREAM = "application/octet-stream",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    WEBP = "image/webp",
    SVG = "image/svg+xml",
    PDF = "application/pdf",
    ZIP = "application/zip",
    CSV = "text/csv",
    TSV = "text/tab-separated-values",
    EVENT_STREAM = "text/event-stream",
    JAVASCRIPT = "application/javascript",
    WEBSOCKET = "application/websocket"
}
